site_name: Sen's Notes
repo_url: https://github.com/slinjhu/notes
theme:
    name: readthedocs
extra_css:
    - stylesheet.css
extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
    - extra.js
markdown_extensions:
    - admonition
    - pymdownx.arithmatex
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.highlight
    - pymdownx.magiclink
    - pymdownx.snippets
    - pymdownx.tabbed
    - pymdownx.mark
    - pymdownx.emoji
    - toc:
        permalink: true

nav:
    - Reading:
        - 'Ruling the waves': 'reading/ruling-the-waves.md'
        - '通往财富自由之路': 'reading/financial-freedom.md'
        - 'Designing data-intensive applications': 'reading/data-intensive-app.md'
        - 'The most important things': 'reading/important-things.md'
        - 'Master class': 'reading/master-class.md'
        - '道理': 'reading/philosophy.md'
    - Software Engineering:
        - 'My favorite quotes related to software engineering': 'software/quotes.md'
        - 'My Configurations': 'software/my-config.md'
        - 'Software quick references': 'software/quick-ref.md'
        - 'Data Structures and Algorithms': 'software/data-structures.md'
    - English:
        - 'Powerful phrases': 'english/powerful-phrases.md'
    - Others:
        - 'Fishing in California': 'others/fishing.md'